---
- name: Install Jenkins 
  hosts: [jenkins_server]
  become: yes 
  become_user: root 
  tasks:
  - name: yum update
    yum:
      name: '*'
      state: latest

  - name: add the jenkins repo
    get_url:
      url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
      dest: /etc/yum.repos.d/jenkins.repo

  - name: import a key file from jenkins-ci
    ansible.builtin.rpm_key:
      state: present 
      key: https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key

  - name: yum update
    yum:
      name: '*'
      state: latest

  - name: install java
    shell: install java-17-amazon-corretto -y

  - name: install jenkins
    yum:
      name: jenkins
      state: latest

  - name: start jenkins
    ansible.builtin.systemd:
      enabled: yes 
      name: jenkins 
      state: started
